const watchLaterConstant = {
    ADD_TO_WATCHLATER: "ADD_TO_WATCHLATER",
    REMOVE_FROM_WATCHLATER: "REMOVE_FROM_WATCHLATER",
    SET_WATCHLATER: "SET_WATCHLATER",
    RESET_WATCHLATER: "RESET_WATCHLATER",
};

export { watchLaterConstant };
